Repository K-BigAnt/Front, pull requests merged in 2024-09, with the labels that each got.

#14 [Chore] : shadcn UI 설치 및 구동
  .gitignore
  components.json
  package.json
  src/app/globals.css
  src/components/ui/button.tsx
  src/lib/utils.ts
  tailwind.config.ts
  yarn.lock
Labels: chore

#16 [Feat]: login page 생성
  public/kakao.svg
  public/logo.svg
  public/naver.svg
  src/app/__tests__/Login.test.tsx
  src/app/__tests__/page.test.tsx
  src/app/api/AxiosInstance.tsx
  src/app/callBack/page.tsx
  src/app/component/Login/Login.tsx
  src/app/component/Login/OAuth.tsx
  src/app/component/Login/Title.tsx
  src/app/component/Logo.tsx
  src/app/login/page.tsx
Labels: feature, API

#10 Feat : auto import 적용
  .pretterrc.json
  .prettierrc
  package.json
  yarn.lock
Labels: feature, bugfix
